tactical_server/heart_rate/views.py
from flask import redirect, render_template, url_for, Blueprint, request
from .forms import HeartForm

from tactical_server.models import Soldier, Vitals

heart_rate_blueprint = Blueprint(
    'heart_rate', __name__, template_folder='templates/heart_rate')


@heart_rate_blueprint.route('/list-heart-rate/<id>')
def list_heart_rate(id):
    """
    Flask Route: '/list-heart-rate/<id>'

    Function to handle requests for displaying a list of a soldier's heart rates. This function is called when the '/list-heart-rate'
    URL is accessed by the Flask app. It queries the database for all heart rate entries associated with the given soldier ID and also
    retrieves the soldier's information. The data is then passed to the 'list-heart-rate.html' template for rendering.

    Args:
    - id (str): Soldier ID for whom the heart rates are to be listed.

    Returns:
    - render_template: HTML page ('list-heart-rate.html') that displays the list of heart rate entries for the selected soldier.
    """

    # Queries all Entries in vitals table with soldier_id entered by user.
    Heart = Vitals.query.filter_by(soldier_id=id).all()
    # Queries soldier using id number entered by user. Returns 404 message is entered id number does not exist in database.
    person = Soldier.query.get_or_404(id)

    # Returns html page that lists vitals entries of selected soldier.
    return render_template('list-heart-rate.html', Heart=Heart, person=person)


# select which section members heart rate to view
@heart_rate_blueprint.route('/view-heart', methods=['POST', 'GET'])
def view_heart():
    """
    Flask Route: '/view-heart'

    Function to handle requests for selecting which section member's heart rate to view. This function is called when the '/view-heart'
    URL is accessed by the Flask app. It uses a form ('HeartForm') to get the ID number of the soldier for whom the heart rate entries
    need to be viewed. If the form is validated, the function redirects to the 'list-heart-rate' page for the selected soldier. Otherwise,
    it renders the 'view-heart.html' template, which includes the form for soldier selection.

    Returns:
    - redirect or render_template: If the form is validated, redirects to the 'list-heart-rate' page. Otherwise, renders 'view-heart.html'
      with the soldier selection form.
    """
    form = HeartForm()  # adds form to be used in function.

    # if the form is validated when the submit button is pressed.
    if request.method == 'POST':
        id = form.id.data  # Extracts id number from data entered in form

        # Redirects to html page to display vitals table entries for entered id number.
        return redirect(url_for('heart_rate.list_heart_rate', id=id))
    # Displays html page that for form to select soldier to view their vitals table entries.
    return render_template('view-heart.html', form=form)

tactical_server/location/views.py
from flask import redirect, render_template, url_for, Blueprint, request

from .forms import LocationForm
from tactical_server.models import Soldier, Location

location_blueprint = Blueprint('location', __name__, template_folder='templates/location')

@location_blueprint.route('/list-location/<id>')
def list_location(id):
    """
    Flask Route: '/list-location/<id>'

    Function to handle requests for selecting a soldier to view the locations they have been. This function is called when the '/list-location'
    URL is accessed by the Flask app. It queries the 'location' table to retrieve all entries with the soldier_id entered by the user. It also
    queries the 'Soldier' table to get information about the soldier with the entered id. If the soldier does not exist, a 404 message is
    returned. The function then renders the 'list-location.html' template, which displays a list of all locations the soldier has been.

    Args:
    - id (int): The ID number of the soldier for whom the locations are to be viewed.

    Returns:
    - render_template: HTML page to display a list of all locations the soldier has been, along with relevant information about the soldier.
    """

    # Queries all Entries in location table with soldier_id entered by user.
    location = Location.query.filter_by(soldier_id=id).all()
    # Queries soldier using id number entered by user. Returns 404 message is entered id number does not exist in database.
    soldier = Soldier.query.get_or_404(id)
    # returns html page to display list of all locations soldier has been.
    return render_template('list-location.html', Location=location, person=soldier)


# displays locations soldier has been
@location_blueprint.route('/view-location', methods=['POST', 'GET'])
def view_location():
    """
    Flask Route: '/view-location'

    Function to handle requests for displaying the locations a soldier has been. This function is called when the '/view-location'
    URL is accessed by the Flask app. It uses the 'LocationForm' to get the soldier's ID from the user. If the form is validated upon
    submission, the function redirects to the 'list-location' route, passing the soldier's ID. This route displays a list of all
    locations the soldier has been.

    Returns:
    - render_template: HTML page containing the form to select a soldier to view their locations.
    - redirect: If the form is validated, redirects to the 'list-location' route to display the locations of the selected soldier.
    """
    form = LocationForm()  # adds form to be used in function.

    # if the form is validated when the submit button is pressed.
    if request.method == 'POST':
        id = form.id.data  # Extracts id number from data entered in form

        # Redirects to webpage to display list of soldiers locations.
        return redirect(url_for('location.list_location', id=id))
    # Returns html for form to select soldier.
    return render_template('view-location.html', form=form)

tactical_server/sections/views.py
from flask import redirect, render_template, url_for, Blueprint, request, jsonify
from .forms import Addammo, CreateSection, DelSection

import json
import datetime

from tactical_server.database import db
from tactical_server.models import Section, Soldier, Vitals, Location

from .convert_to_dict import convert_to_dict
from geopy import distance
from .lat_long_to_grid_reference import lat_long_to_grid_reference

section_blueprint = Blueprint(
    'sections', __name__, template_folder='templates/sections')


@section_blueprint.route('/add-section', methods=['GET', 'POST'])
def add_section():
    """
    Flask Route: '/add-section' (GET and POST)

    Function to handle requests for adding a new section. This function is called when the '/add-section' URL is
    accessed by the Flask app, and it supports both GET and POST methods. It uses the 'CreateSection' form to gather
    user input.

    If the form is validated on submission, it extracts the section's ID and ammunition from the form, creates a new
    section with default values, and adds it to the database. Then, it redirects to the 'section-overview' page.

    Returns:
    - str: Rendered HTML page ('add-section.html') with the 'CreateSection' form for creating a new section.
            Or, redirects to the 'section-overview' page if a new section is successfully added.
    """
    form = CreateSection()  # adds CreateSection form to be used in function.

    # if the form is validated when the submit button is pressed.
    # if form.validate_on_submit():
    if request.method == "POST":

        id = form.id.data  # Extracts id number from data entered in form.
        # Extracts Ammunition from data entered in form.
        SectionAmmo = form.SectionAmmo.data

        # Creates new section member form data entered in form.
        new_sec = Section(id, SectionAmmo)
        db.session.add(new_sec)
        db.session.commit()  # Saves change made to database.

        # Redirects to page that displays Section information.
        return redirect(url_for('sections.section_overview'))

    # Returns Html page for form to create a new section.
    return render_template('add-section.html', form=form)


# function to add a section
@section_blueprint.route('/add-amunition', methods=['GET', 'POST'])
def add_ammo():
    """
    Flask Route: '/add-amunition' (GET and POST)

    Function to handle requests for adding ammunition to a section. This function is called when the '/add-amunition'
    URL is accessed by the Flask app, and it supports both GET and POST methods. It uses the 'Addammo' form to gather
    user input.

    If the form is validated on submission, it extracts the section's ID and ammunition from the form, queries the
    database to get the corresponding section, adds the ammunition to the section, and updates the database. Then, it
    redirects to the 'section-overview' page.

    Returns:
    - str: Rendered HTML page ('add-amunition.html') with the 'Addammo' form for adding ammunition to a section.
            Or, redirects to the 'section-overview' page if ammunition is successfully added to the section.
    """
    form = Addammo()  # adds form to be used in function.

    # if the form is validated when the submit button is pressed.
    if request.method == "POST":

        id = form.id.data  # Extracts id number from data entered in form
        # Extracts ammunition from data enter in form.
        amuntion_added = form.SectionAmmo.data

        # Queries database using entered id number returns 404 message if number entered is not in database.
        resupply = Section.query.get_or_404(id)
        # Takes ammunition added in form and adds it to section ammunition.
        resupply.section_amunition += amuntion_added
        db.session.add(resupply)  # Adds new entry to database.
        db.session.commit()  # Saves change to database.

        # redirects to page that displays section information.
        return redirect(url_for('sections.section_overview'))

    # returns html page that displays page to add ammunition to section.
    return render_template('add-amunition.html', form=form)


# Displays section overview to user
@section_blueprint.route('/section-overview')
def section_overview():
    """
    Flask Route: '/section-overview'

    Function to handle requests for displaying the section overview to the user. This function is called when the
    '/section-overview' URL is accessed by the Flask app.

    Returns:
    - str: Rendered HTML page ('section-overview.html') containing the overview of the section.
    """

    # Returns html page for overview of section.
    return render_template('section-overview.html')


# Remove section
@section_blueprint.route('/delete-section', methods=['POST', 'GET'])
def delete_section():
    """
    Route handler to remove a section along with its associated soldiers.

    This function handles HTTP GET and POST requests for deleting a section. If the provided form is validated,
    it extracts the section ID and deletes all soldiers associated with that section. Finally, it deletes the
    specified section from the database.

    Parameters:
    - None

    Returns:
    - GET Request: Renders the 'delete-section.html' template with the deletion form.
    - POST Request: Redirects to the 'section-overview' route after successfully deleting the section and associated soldiers.
    """

    form = DelSection()  # adds form to be used in function.

    # if the form is validated when the submit button is pressed.
    if request.method == "POST":
        id = form.id.data  # Extracts id number from data entered in form
        # When section is deleted. Queries all soldiers with same section id and deletes them.
        soldiers = Soldier.query.filter_by(section_id=id).all()

        for i in soldiers:  # for loop to iterate through soldiers returned by query.
            db.session.delete(i)  # deletes soldier.
            db.session.commit()  # saves change to database.

        # Queries section using entered id data taken from form. Returns 404 message if no entry exists.
        section = Section.query.get_or_404(id)
        db.session.delete(section)  # Deletes section.
        db.session.commit()  # Saves change to database.
        # redirects to page that displays section information.
        return redirect(url_for('sections.section_overview'))

    # Returns html page of form to delete section.
    return render_template('delete-section.html', form=form)


# list all members in section
@section_blueprint.route('/list-section-members')
def list_section_members():
    """
    Flask Route: '/list-section-members'

    Function to handle requests for listing all members in a section. This function is called when the '/list-section-members' URL is accessed
    by the Flask app. It returns an HTML page ('list-section-members.html') that displays a list of soldiers in the section.

    Returns:
    - render_template: HTML page for displaying the list of soldiers in the section.
    """

    # Returns html page that that displays soldiers in section.
    return render_template('list-section-members.html')

# sends section information to a page in json script format.


@section_blueprint.route('/section', methods=['GET'])
def section_json_information():
    """
    Flask Route: '/section'

    Function to handle requests for section information in JSON script format. This function is called when the '/section'
    URL is accessed by the Flask app using the GET method. It queries all section information from the database, formats it
    into a list of dictionaries, each representing a section, and returns the result as a JSON script.

    Returns:
    - str: JSON script containing section information, formatted as a list of dictionaries.
    """

    sections = Section.query.all()  # Queries all section information.

    sections_json = []  # blank list to store json information.
    # For loop to iterate through Queried data and store it in a list printed in json format.
    for i in sections:
        section = {"id": i.id, "SectionAmmo": i.section_amunition, "SectionStrength": i.section_strength, "SectionLocation": i.section_location,
                   "SectionOK": i.section_ok, "SectionCasualty": i.section_casualty, "SectionBattery": i.section_battery}  # Queried information printed as json.
        sections_json.append(section)  # information appended to list.

    # print(json.dumps(sections))
    # list converted to json and printed to page'/section'
    return json.dumps(sections_json)


# sends section information to a page in json script format.
@section_blueprint.route('/soldiers', methods=['GET'])
def soldier_json_information():
    """
    Flask Route: '/soldiers'

    Function to handle requests for soldier information in JSON script format. This function is called when the '/soldiers'
    URL is accessed by the Flask app using the GET method. It queries all soldier information from the database, formats it
    into a list of dictionaries, each representing a soldier, and returns the result as a JSON script.

    Returns:
    - str: JSON script containing soldier information, formatted as a list of dictionaries.
    """

    section = Soldier.query.all()  # Queries all Soldier information.

    sections = []  # blank list to store json information.
    # For loop to iterate through Queried data and store it in a list printed in json format.
    for i in section:
        soldier = {"id": i.id, "name": i.name, "role": i.role, "Ident": i.identity_check, "LastHR": i.last_heart_rate, "currentLocation": i.current_location,
                   "Distance": i.distance_traveled, "TIME": i.last_update_time, "Rndsfired": i.ammunition_expended, "RifleBat": i.rifle_sensor_battery_level, "State": i.status,
                   "ArmourBat": i.armour_sensor_battery_level, "HubBattery": i.hub_sensor_battery_level}  # Queried information printed as json.

tactical_server/templates/Addamunition.html
{% extends "base.html" %}<!--Extends content from the base html page-->
{% block  content %}<!--Extends content from the base html page-->
<div class="jumbotron"><!--Adds bootstrap jumbotron style to page -->
  <h1>Add Amunition to Section</h1><!--Prints name of page to user -->
  <p>Fill in Section Number, and Ammunition to Add amunition to that Section.</p><!--Prints instructions to the user -->
  <form method="POST"><!--Form opening tag with post method included -->
    {{form.hidden_tag()}}
    {{form.id.label}} {{form.id()}}<!--input section number -->
    {{form.SectionAmmo.label}} {{form.SectionAmmo()}}<!--input total ammunition for the section -->
    {{form.submit()}}<!--Submit button for form press to send form information to flask -->

  </form>

</div>

{% endblock %}

tactical_server/templates/SectionOverview.html
{% extends "base.html" %}<!--Extends content from the base html page-->

{% block  scripts %}<!--Extends script from the base html page-->

<script>

  //Javascript function to update information displayed on page without haveing to refresh the page
  function update(){

  //Remove values currently printed on the page or the following function will just append more data to the page using the tag "section".
    $("#section tbody > tr").remove();

      //Gets json data from the page "/soldiers" and stores it in an array 'result'
    $.getJSON("/section",function(result){

      //increments through each value in array result to allow it to beused to prind data to webpage.
      $.each(result,function(i){


        //1st variable contains the section number, total amunition in the section, the strength of the section, the location of the section and the number of section members that are fit for duty.
        var bit1 = "<tr><td scope='row'>" + result[i].id +"</td><td>"+ result[i].SectionAmmo + "</td><td>"
            + result[i].SectionStrength + "</td><td>" + result[i].SectionLocation + "</td><td class='table-success'>" + result[i].SectionOK + "</td>";

        //Second variable contains number of casulties in the section. displays green if there are no casulties otherwise displays orange
        if(result[i].SectionCasualty == 0){
          var bit2 = "<td class = 'table-success'>"+ result[i].SectionCasualty +" </td>";
        }else{
          var bit2 = "<td class = 'table-warning'>"+ result[i].SectionCasualty +" </td>";
        }

        //8th variable displays battery level, changes from green to orange to red as battery level drops.
        if(result[i].SectionBattery>60){
          var bit3 = "<td><div class='progress'><div class='progress-bar bg-success' style='width:" + result[i].SectionBattery +"%;'>" + result[i].SectionBattery + "% </div></div></td>";
        }else if(result[i].SectionBattery>30){
          var bit3 = "<td><div class='progress'><div class='progress-bar bg-warning' style='width:" + result[i].SectionBattery +"%;'>" + result[i].SectionBattery + "% </div></div></td>";
        }else{
          var bit3 = "<td><div class='progress'><div class='progress-bar bg-danger' style='width:" + result[i].SectionBattery +"%;'>" + result[i].SectionBattery + "% </div></div></td>";
        }


          //Concatenates variables together to create table row to be displayed on the web page.
        var row = bit1 + bit2 + bit3;
        $("#section tbody").append(row);

      });

    });

  }

  $(document).ready(function(){

    update();//initial call of update function to display values when web page is viewed.

    setInterval(function()//calls update function every 5 seconds to update page.
    {
      update();
    },5000)
  });



</script>

{% endblock %}<!--Extends content from the base html page-->


{% block  content %}<!--Extends content from the base html page-->


<div class="jumbotron"><!--Adds jumbotron style to page-->
  <h1>Section</h1><!--Displays name of table-->

  <table id = "section" class="table"><!--Creates table to display data, bootstrap class 'table' added to improve style of table id tag 'section' used by Javascript function to apply data to the table-->
    <thead class="thead-dark"><!--Bootstrap style gives a dark backround to table headings-->
      <tr><!--Table row-->
        <th scope="col">Section Number </th><!--Column heading-->
        <th scope="col">Ammunition </th><!--Column heading-->
        <th scope="col">Strength </th><!--Column heading-->
        <th scope="col">Location </th><!--Column heading-->
        <th scope="col">OK</th><!--Column heading--><!--Column heading-->
        <th scope="col">Casualty</th><!--Column heading-->
        <th scope="col">Battery </th><!--Column heading-->
      </tr><!--Table row end-->
    </thead>
    <tbody>





    </tbody>
  </table>


</div>

{% endblock %}

tactical_server/templates/ViewHeart.html
{% extends "base.html" %}<!--Extends content from the base html page-->
{% block  content %}<!--Extends content from the base html page-->
<div class="jumbotron"><!--Extends content from the base html page-->
  <h1>View Heart rate</h1><!--Prints name of page to user -->
  <p>Enter ID number of Soldier to view heart rate over time.</p><!--Prints instructions to the user -->
  <form method="POST"><!--Form opening tag with post method included -->
    {{form.hidden_tag()}}
    {{form.id.label}}{{form.id}}<!--input for the army number of the soldier -->
    {{form.submit}}<!--Submit button for form press to send form information to flask -->

  </form>

</div>

{% endblock %}

tactical_server/templates/ViewLocation.html
{% extends "base.html" %}<!--Extends content from the base html page-->
{% block  content %}<!--Extends content from the base html page-->
<div class="jumbotron"><!--Extends content from the base html page-->
  <h1>View Location</h1><!--Prints name of page to user -->
  <p>Enter ID number of Soldier to view Location over time.</p><!--Prints instructions to the user -->
  <form method="POST">
    {{form.hidden_tag()}}
    {{form.id.label}}{{form.id}}<!--input for the army number of the soldier -->
    {{form.submit}}<!--Submit button for form press to send form information to flask -->

  </form>

</div>

{% endblock %}

tactical_server/templates/add.html
{% extends "base.html" %}<!--Extends content from the base html page-->
{% block  content %}<!--Extends content from the base html page-->
<div class="jumbotron"><!--Adds bootstrap jumbotron style to page -->
  <h1>Add Section Member</h1><!--Prints name of page to user -->
  <p>Fill in Service number, name and Section Number to add person to Section.</p><!--Prints instructions to the user -->

  <form method="POST"><!--Form opening tag with post method included -->

            {{form.hidden_tag()}}
            {{form.id.label}} {{form.id()}}<!--input for the army number of the soldier -->
            {{form.name.label}} {{form.name()}}<!--Input for the soldiers name -->
            {{form.role.label}} {{form.role()}}<!--Input for the role of the soldier -->
            {{form.section_id.label}} {{form.section_id()}}<!--Input section id of soldier -->
            {{form.submit()}}<!--Submit button for form press to send form information to flask -->

  </form>

</div>

{% endblock %}<!--Ends block -->

tactical_server/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <!--This base html file extends its contents to all other  using the block command this allows the a navbar to be added to all pages with minimum code -->


  <!--Belov are links to the bootstrap files held in the static folder-->
    <link rel="stylesheet" href="/static/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="/static/jquery-3.4.1.js" ></script>
    <script src="/static/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="/static/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    {% block  scripts %}<!--labels the block of scripts to extend to other html pages -->

    {% endblock %}<!--ends the block -->

    <title>Section Page</title><!--prints the title of the page in the tab at the top of the page -->
  </head>
  <body>

    <nav class="navbar navbar-expand-sm navbar-light bg-success mb-3"><!--Nav bar created with bootstrap style included -->

      <div class="container"><!--Container to hold the links in the navbar -->
        <a class="navbar-brand" href="#">Section Managment System</a><!--prints title on left hand side of the page -->
        <ul class="navbar-nav">
          <li class="nav-item">
              <a class = "nav-item nav-link" href="{{url_for('index')}}">Home</a><!--Link to return to home page -->
          </li>
           <li class="nav-item dropdown"><!-- -->
               <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Update Section</a><!--drop down link for options to update the section -->
                 <div class="dropdown-menu">
                  <a class = "dropdown-item" href="{{url_for('sections.add_section')}}">Create Section</a><!--Link to a page to add a section -->
                  <a class = "dropdown-item" href="{{url_for('sections.delete_section')}}">Remove Section</a><!--Link to a page to remove a section member -->
                  <a class = "dropdown-item" href="{{url_for('soldiers.add_soldier')}}">Add to Section</a><!--Link to a page to Add a person to the section -->
                  <a class = "dropdown-item" href="{{url_for('soldiers.delete_soldier')}}">Remove from Section</a><!--Link to a page to remove a person from the section -->
                  <a class = "dropdown-item" href="{{url_for('sections.add_ammo')}}">Add Amunition to Section</a><!--Link to a page to Add ammunition to the section -->
                </div>
            </li>
            <li class="nav-item dropdown"><!-- -->
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">View Section</a><!--drop down menu to view section -->
                  <div class="dropdown-menu">
                    <a class = "dropdown-item" href="{{url_for('sections.section_overview')}}">Section Overview</a><!--Displays Owerview of section information -->
                    <a class = "dropdown-item" href="{{url_for('sections.list_section_members')}}">List of Section</a><!--Displays a detailed list of all members of the section-->
                    <a class = "dropdown-item" href="{{url_for('heart_rate.view_heart')}}">View Soldier Heart rate</a><!--Displays the heart rate over time of a selected soldier -->
                    <a class = "dropdown-item" href="{{url_for('location.view_location')}}">View Soldier Location</a><!--Views the location over time of the members of a section -->
                  </div>
              </li>
        </ul>

      </div>

    </nav>

    {% block  content %}<!--Block content to be extended to other pages  -->

    {% endblock %}<!--End of block -->


  </body>
</html>

tactical_server/templates/delete.html
{% extends "base.html" %}<!--Extends content from the base html page-->
{% block  content %}<!--Extends content from the base html page-->
<div class="jumbotron"><!--Adds bootstrap jumbotron style to page -->
  <h1>Remove Member from Section</h1><!--Prints name of page to user -->
  <p>Enter Service number of Section member to Remove.</p><!--Prints instructions to the user -->
  <form method="POST"><!--Form opening tag with post method included -->
    {{form.hidden_tag()}}
    {{form.id.label}}{{form.id}}<!--input for the army number of the soldier -->
    {{form.submit}}<!--Submit button for form press to send form information to flask -->

  </form>

</div>

{% endblock %}

tactical_server/templates/deleteSection.html
{% extends "base.html" %}<!--Extends content from the base html page-->
{% block  content %}<!--Extends content from the base html page-->
<div class="jumbotron"><!--Adds bootstrap jumbotron style to page -->
  <h1>Remove Section</h1><!--Prints name of page to user -->
  <p>Enter Section number to delete Section.</p><!--Prints instructions to the user -->
  <form method="POST"><!--Form opening tag with post method included -->
    {{form.hidden_tag()}}
    {{form.id.label}}{{form.id}}<!--input for section number -->
    {{form.submit}}<!--Submit button for form press to send form information to flask -->

  </form>

</div>

{% endblock %}

tactical_server/templates/home.html
{% extends "base.html" %}<!--Extends content from the base html page-->
{% block  content %}<!--Extends content from the base html page-->
<div class="jumbotron"><!--Adds bootstrap jumbotron style to page -->
  <h1>Welcome!</h1><!--Prints Welcome to user -->

</div>

{% endblock %}

tactical_server/templates/index.html
{% extends "base.html" %}<!--Extends content from the base html page-->
{% block  content %}<!--Extends content from the base html page-->
<div class="jumbotron"><!--Adds bootstrap jumbotron style to page -->
  <h1>Welcome!</h1><!--Prints Welcome to user -->

</div>

{% endblock %}

tactical_server/templates/listHeartRate.html
{% extends "base.html" %}<!--Extends content from the base html page-->
{% block  content %}<!--Extends content from the base html page-->
<div class="jumbotron"><!--Adds jumbotron style to page-->
  <h1>{{person.id}} {{person.name}} Heart Rate</h1><!--Prints the name and Id of the soldier whos heart rate you are viewing-->

  <table class="table"><!--Creates table to display data, bootstrap class 'table' added to improve style of table-->
    <thead class="thead-dark"><!--Bootstrap style gives a dark backround to table headings-->
      <tr><!--Creates a row in the table-->
        <th scope="col">Heart Rate </th><!--Column heading-->
        <th scope="col">Time </th><!--Column heading-->
      </tr>
    </thead>
    <tbody><!--body of table-->

      {% for pte in Heart %}<!--For loop used to print all values to the page-->
      <tr><!--Table row-->

      <td scope="row">{{pte.HR}}</td><!--Prints value for heart rate-->
      <td>{{pte.TIME}}</td><!--prints value for time-->

      </tr>

      {% endfor %}<!--end of for loop-->

    </tbody>
  </table>

</div>

{% endblock %}

tactical_server/templates/listLocation.html
{% extends "base.html" %}<!--Extends content from the base html page-->
{% block  content %}<!--Extends content from the base html page-->
<div class="jumbotron"><!--Adds jumbotron style to page-->
  <h1>{{person.id}} {{person.name}} Location</h1><!--Prints the name and Id of the soldier whos location you are viewing-->

<table class="table"><!--Creates table to display data, bootstrap class 'table' added to improve style of table-->
  <thead class="thead-dark"><!--Bootstrap style gives a dark backround to table headings-->
    <tr><!--Creates a row in the table-->
      <th scope="col">Longitude </th><!--Column heading-->
      <th scope="col">Latitude </th><!--Column heading-->
      <th scope="col">Grid reference </th><!--Column heading-->
      <th scope="col">Time </th><!--Column heading-->
    </tr>
  </thead>
  <tbody>
    
    {% for pte in Location %}<!--For loop used to print all values to the page-->
    <tr><!--Table row-->

    <td scope="row">{{pte.lat}}</td><!--Prints value for Latitude-->
    <td>{{pte.long}}</td><!--Prints value for Longitude-->
    <td>{{pte.GRID}}</td><!--Prints value for Grid reference-->
    <td>{{pte.TIME}}</td><!--Prints value for time-->

    </tr>

    {% endfor %}<!--end of for loop-->

  </tbody>
</table>

</div>

{% endblock %}